apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dni-function
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.dni-function: semver:~1.0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dni-function
    spec:
      containers:
      - name: dni-function
        image: jagorddemoappacr4.azurecr.io/demo-app:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: dni-function
spec:
  type: LoadBalancer
  ports:
  - name:
    port: 80
    targetPort: 8000
  selector:
    app: dni-function
